### ISSUE TITLE
[bug] Svelte config file resolving on Windows 

### ISSUE THREAD

**Issue by sz3ry** [nickbreaton/vitest-svelte-kit#1]
Helloo!

As described [in this Vite issue](https://github.com/vitejs/vite/issues/1712#issue-793480332), there is a problem on Windows to get the file with ES modules 

There is an error like this: 

`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

Solution is easy, one liner, 

```js
import {pathToFileURL} from 'url'

const resolvedConfigFile = path.resolve(process.cwd(), "svelte.config.js");
const file = pathToFileURL(resolvedConfigFile).href;

```

**Comment by nickbreaton** [comment]
Thanks for the report and the fix! I've added windows as a runner in CI to avoid this coming back, and published the fix in version `0.0.5`. 

Going to close for now. If you wouldn't mind giving it another try just to verify, that would be awesome!
