### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by ccadieux** [nickbreaton/vitest-svelte-kit#5]
Currently when using this with typescript. 

```
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json"

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json"
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Further if you use ts instead of js for the tests you get the following error and the tests don't run.
```
 FAIL  src/lib/button/button.test.ts [ src/lib/button/button.test.ts ]
Error: failed to resolve "extends":"./.svelte-kit/tsconfig.json" in <Project path>/tsconfig.json
 ❯ resolveExtends node_modules/vite/dist/node/chunks/dep-9c153816.js:22266:11
 ❯ parseExtends node_modules/vite/dist/node/chunks/dep-9c153816.js:22250:34
 ❯ parse$e node_modules/vite/dist/node/chunks/dep-9c153816.js:22201:24
 ❯ async loadTsconfigJsonForFile node_modules/vite/dist/node/chunks/dep-9c153816.js:22547:24
 ❯ async transformWithEsbuild node_modules/vite/dist/node/chunks/dep-9c153816.js:22380:36
 ❯ async TransformContext.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:22468:32
 ❯ async Object.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30
 ❯ async doTransform node_modules/vite/dist/node/chunks/dep-9c153816.js:53030:29
```

**Comment by jmagrippis** [comment]
I don't think this is a problem with `vitest` or `vitest-svelte-kit`. It's that your `./.svelte-kit` directory doesn't exist. It will be created if you run `npm run dev` or `npm run build` before running your tests.

I've had this problem on CI, so I've added my build step before my test step:

https://github.com/jmagrippis/with-svelte/blob/main/.github/workflows/main.yaml#L36

I don't know if that's the best way to get around this, but it defo works for me 🙂

Maybe `@sveltejs/kit` could export their tsconfig so we could require it from the library and not from the local directory, but that's a different discussion!

**Comment by nickbreaton** [comment]
Whoops failed to notice this was the same issue as here (https://github.com/nickbreaton/vitest-svelte-kit/issues/7). As @jmagrippis pointed out my recommendation would also be to build before running tests. Not ideal, but there's a link in that issue to a Svelte Kit discussion around officially supporting exposing a vite config. Maybe this is something they could consider as well.
